# Generated by Django 5.1.5 on 2025-05-08 07:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_comment_recipe_comment_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcontent',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_contents', to=settings.AUTH_USER_MODEL),
        ),
    ]
